project_id = "zfxdjbpjxpgreymebpsr"

[functions.secure-auth]
verify_jwt = false

[functions.sms-webhook]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.send-weekly-recap]
verify_jwt = false

[functions.send-trial-reminders]
verify_jwt = false

[functions.send-milestone-message]
verify_jwt = false

[functions.send-signup-confirmation]
verify_jwt = false

[functions.delete-user-admin]
verify_jwt = true