project_id = "zfxdjbpjxpgreymebpsr"

[functions.sms-test-suite]
verify_jwt = false

[functions.sms-comprehensive-test]
verify_jwt = true

[functions.sms-monitoring-dashboard]
verify_jwt = false

[functions.sms-health-check]
verify_jwt = false

[functions.sms-test-interface]
verify_jwt = false

[functions.sms-webhook]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.send-weekly-recap]
verify_jwt = false

[functions.send-milestone-message]
verify_jwt = true

[functions.send-trial-reminders]
verify_jwt = false

[functions.sync-cron-secret]
verify_jwt = false
